 version: 'version'
 services:
    backend:
      image: nginx    
      environment:
          DB_HOST: db
          DB_DATABASE: admin
          DB_USER: root
          DB_PASSWORD: root
          DB_PORT: 3306
          ports:
          - "8000:8000"
          depends_on:
            - db
    db:
      image: mysql:5.6
      restart: always
    
      environment:
    MYSQL_DATABASE: admin
    MYSQL_USER: root
    MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - db_data:/var/lib/mysql