name: CD - Build & Deploy & Release

on:
  push:
    branches:
    - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      
      - name: Delete tests
        run: sudo rm -rf /src/tests/
        
        
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          name: DEV
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
          key: ${{ secrets.SSH_PRIVATE_KEY }} 
          config: |
            cd /var/www/Hospital/client
            npm install
            npm run build -f
          
